import { CivicDomainMetadata } from '@/types/domain';

export const CIVIC_DOMAINS: CivicDomainMetadata[] = [
  {
    id: 'identity',
    title: 'Citizen Identity & Governance',
    shortName: 'Identity',
    description: 'Barangay ID, Civil Registry, Citizen Feedback & Governance Surveys',
    icon: 'person.text.rectangle.fill',
    color: '#2563EB',
    subCategories: ['Barangay ID', 'Civil Registry', 'Citizen Feedback', 'Governance Surveys'],
  },
  {
    id: 'social-services',
    title: 'Social Services & Welfare',
    shortName: 'Social Services',
    description: 'AICS Financial Aid, PWD/Senior Citizen Registry, Solo Parent & Livelihood Grants',
    icon: 'heart.text.square.fill',
    color: '#EC4899',
    subCategories: ['AICS Aid', 'PWD & Senior', 'Solo Parent', 'Livelihood Assistance'],
  },
  {
    id: 'health',
    title: 'Health & Sanitation',
    shortName: 'Health',
    description: 'Health Center Appointments, Immunization Logs, Sanitation Permits & Wastewater Clearance',
    icon: 'cross.case.fill',
    color: '#10B981',
    subCategories: ['Health Center', 'Immunization Tracker', 'Sanitation Permits', 'Wastewater Clearance'],
  },
  {
    id: 'education',
    title: 'Education & Scholarships',
    shortName: 'Education',
    description: 'City Scholarship Applications, Student Registry & Educational Financial Aid',
    icon: 'book.closed.fill',
    color: '#8B5CF6',
    subCategories: ['City Scholarships', 'Student Registry', 'Aid Distribution'],
  },
  {
    id: 'emergency',
    title: 'Emergency, DRRM & Safety',
    shortName: 'Emergency SOS',
    description: 'Real-time Hazard Maps, Relief Goods Tracker & Instant Incident SOS Dispatch Log',
    icon: 'shield.fill',
    color: '#EF4444',
    badgeCount: 2,
    subCategories: ['Hazard Maps', 'Relief Tracker', 'Incident SOS Log'],
  },
  {
    id: 'housing',
    title: 'Urban Planning & Housing',
    shortName: 'Housing',
    description: 'Zoning Clearance, Socialized Housing Beneficiaries & Occupancy Permits',
    icon: 'building.2.fill',
    color: '#F59E0B',
    subCategories: ['Zoning Clearance', 'Housing Beneficiaries', 'Occupancy Permits'],
  },
  {
    id: 'business',
    title: 'Business, Permits & Licensing',
    shortName: 'Business',
    description: 'New & Renewal Business Permits, Building Permits & E-Permit Tracker',
    icon: 'briefcase.fill',
    color: '#06B6D4',
    subCategories: ['Business Permit', 'Building Permit', 'E-Permit Tracker'],
  },
  {
    id: 'treasury',
    title: 'Revenue Collection & Treasury',
    shortName: 'Treasury',
    description: 'Real Property Tax (RPT), Business Tax, Market Stall Fees & Digital Payments',
    icon: 'creditcard.fill',
    color: '#059669',
    subCategories: ['Property Tax (RPT)', 'Business Tax', 'Market Stalls', 'Digital Pay'],
  },
  {
    id: 'transport',
    title: 'Transport & Mobility',
    shortName: 'Transport',
    description: 'Tricycle/PUV Franchise Database, Traffic Violations & Vehicle Registration',
    icon: 'car.fill',
    color: '#D97706',
    subCategories: ['PUV Database', 'Franchise Renewal', 'Traffic Violations', 'Vehicle Registration'],
  },
  {
    id: 'facilities',
    title: 'Public Assets & Facilities',
    shortName: 'Facilities',
    description: 'Municipal Cemetery, Park Reservations, Water & Drainage Maintenance Requests',
    icon: 'wrench.and.screwdriver.fill',
    color: '#64748B',
    subCategories: ['Cemetery Registry', 'Park Reservations', 'Water & Drainage'],
  },
];
