import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F6F8FA",
  },
  scrollContent: {
    paddingHorizontal: 0,
    paddingTop: 0,
    paddingBottom: 110,
  },
  heroContainer: {
    width: "100%",
    height: 190,
    overflow: "hidden",
  },
  heroBackground: {
    width: "100%",
    height: "100%",
    justifyContent: "flex-start",
  },
  heroImageStyle: {
    opacity: 0.95,
  },
  heroOverlay: {
    paddingTop: Platform.OS === "android" ? 18 : 14,
    paddingHorizontal: 20,
  },
  heroGreetingText: {
    fontSize: 22,
    fontWeight: "800",
    letterSpacing: -0.3,
    marginBottom: 4,
  },
  heroSubText: {
    fontSize: 14,
    fontWeight: "600",
  },
  bodyContent: {
    paddingHorizontal: 16,
  },
  civicCard: {
    borderRadius: 24,
    padding: 16,
    marginTop: -44,
    borderWidth: 1,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 14,
    elevation: 4,
    marginBottom: 16,
  },
  civicCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  civicCardTitle: {
    fontSize: 18,
    fontWeight: "800",
    letterSpacing: -0.2,
  },
  viewAllRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
  viewAllText: {
    fontSize: 13,
    fontWeight: "600",
  },
  pillarGrid: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  pillarCard: {
    flex: 1,
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  pillarIconBadge: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  pillarValue: {
    fontSize: 20,
    fontWeight: "800",
    lineHeight: 24,
    marginBottom: 4,
    textAlign: "center",
  },
  pillarValueStatus: {
    fontSize: 14,
    fontWeight: "800",
    lineHeight: 24,
    marginBottom: 4,
    textAlign: "center",
  },
  pillarLabel: {
    fontSize: 11,
    fontWeight: "500",
    textAlign: "center",
    lineHeight: 14,
  },
  paginationRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 14,
    gap: 5,
  },
  paginationPillActive: {
    width: 24,
    height: 4,
    borderRadius: 2,
  },
  paginationPill: {
    width: 16,
    height: 4,
    borderRadius: 2,
  },
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    height: 50,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 16,
    paddingHorizontal: 14,
    marginBottom: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 2,
  },
  searchInput: {
    flex: 1,
    marginLeft: 10,
    fontSize: 13,
    color: "#111827",
  },
  clearBtn: {
    paddingHorizontal: 4,
  },
  clearText: {
    fontSize: 14,
    fontWeight: "700",
  },
  scanBtn: {
    paddingHorizontal: 4,
    justifyContent: "center",
    alignItems: "center",
  },
  sectionBlock: {
    marginBottom: 28,
  },
  lastSection: {
    marginBottom: 0,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#111827",
  },
  sectionLink: {
    fontSize: 13,
    fontWeight: "600",
    color: "#176B87",
  },
  serviceGrid: {
    gap: 10,
  },
  serviceItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 14,
    paddingVertical: 13,
    paddingHorizontal: 14,
    gap: 12,
  },
  serviceIconBox: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  serviceTextBlock: {
    flex: 1,
  },
  serviceItemTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#111827",
    marginBottom: 1,
  },
  serviceItemSub: {
    fontSize: 12,
    color: "#667085",
  },
  shortcutRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 14,
    overflow: "hidden",
  },
  shortcutItem: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    gap: 6,
    backgroundColor: "transparent",
  },
  shortcutDivider: {
    width: 1,
    height: 20,
  },
  shortcutText: {
    fontSize: 13,
    fontWeight: "600",
  },
  activityCard: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 14,
    overflow: "hidden",
  },
  activityRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 13,
    gap: 12,
  },
  activityIconBox: {
    width: 34,
    height: 34,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
  },
  activityInfo: {
    flex: 1,
  },
  activityTitle: {
    fontSize: 13,
    fontWeight: "600",
    color: "#111827",
    marginBottom: 2,
  },
  activityMeta: {
    fontSize: 11,
    color: "#667085",
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  statusBadgeText: {
    fontSize: 11,
    fontWeight: "700",
  },
  rowDivider: {
    height: 1,
    marginHorizontal: 14,
  },
  featuredCard: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 14,
    flexDirection: "row",
    overflow: "hidden",
    marginBottom: 10,
  },
  featuredAccent: {
    width: 4,
    backgroundColor: "#DC2626",
  },
  featuredContent: {
    flex: 1,
    padding: 14,
  },
  featuredTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  emergencyBadge: {
    backgroundColor: "#FEE2E2",
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 5,
  },
  emergencyBadgeText: {
    fontSize: 10,
    fontWeight: "800",
    color: "#B91C1C",
    letterSpacing: 0.5,
  },
  featuredDate: {
    fontSize: 11,
    color: "#667085",
  },
  featuredTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#111827",
    lineHeight: 19,
    marginBottom: 5,
  },
  featuredSummary: {
    fontSize: 12,
    color: "#667085",
    lineHeight: 17,
    marginBottom: 10,
  },
  featuredFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: "#F3F4F6",
    paddingTop: 9,
  },
  featuredDept: {
    fontSize: 11,
    color: "#667085",
    flex: 1,
  },
  readRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
  },
  readText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#176B87",
  },
  secondaryRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 14,
    paddingVertical: 13,
    paddingHorizontal: 14,
  },
  secondaryLeft: {
    flex: 1,
    paddingRight: 8,
  },
  secondaryCategory: {
    fontSize: 10,
    fontWeight: "700",
    color: "#176B87",
    letterSpacing: 0.5,
    marginBottom: 3,
  },
  secondaryTitle: {
    fontSize: 13,
    fontWeight: "600",
    color: "#111827",
    marginBottom: 2,
  },
  secondaryDate: {
    fontSize: 11,
    color: "#667085",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.65)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  qrModalContainer: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 24,
    width: "100%",
    alignItems: "center",
  },
  announcementModalContainer: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 20,
    width: "100%",
  },
  qrModalHeader: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  qrModalTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#0F172A",
  },
  modalCloseBtn: {
    padding: 4,
  },
  modalCloseText: {
    fontSize: 18,
    color: "#64748B",
    fontWeight: "700",
  },
  qrCodeBox: {
    padding: 16,
    backgroundColor: "#F8FAFC",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    marginBottom: 14,
  },
  qrCitizenName: {
    fontSize: 18,
    fontWeight: "900",
    color: "#0F172A",
  },
  qrCitizenId: {
    fontSize: 13,
    fontWeight: "700",
    color: "#176B87",
    marginBottom: 8,
  },
  qrInstructionText: {
    fontSize: 12,
    color: "#64748B",
    textAlign: "center",
    marginTop: 12,
    lineHeight: 18,
  },
  primaryModalBtn: {
    backgroundColor: "#176B87",
    borderRadius: 14,
    paddingVertical: 12,
    width: "100%",
    alignItems: "center",
    marginTop: 16,
  },
  primaryModalBtnText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "700",
  },
  ancModalTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: "#0F172A",
    marginBottom: 4,
    lineHeight: 22,
  },
  ancModalDate: {
    fontSize: 11,
    color: "#64748B",
  },
  ancModalDept: {
    fontSize: 11,
    fontWeight: "700",
    color: "#176B87",
    marginTop: 2,
  },
  ancModalDivider: {
    height: 1,
    backgroundColor: "#E2E8F0",
    marginVertical: 12,
  },
  ancModalBody: {
    fontSize: 13,
    color: "#334155",
    lineHeight: 20,
  },
});
