import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8FAFC",
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 110,
  },
  loadingBox: {
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  loadingText: {
    fontSize: 12,
    color: "#176B87",
    fontWeight: "600",
  },
  headerCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
    marginBottom: 16,
  },
  avatarRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  avatarCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#176B87",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  avatarText: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "800",
  },
  onlineBadgeDot: {
    position: "absolute",
    bottom: 2,
    right: 2,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: "#16A34A",
    borderWidth: 2,
    borderColor: "#FFFFFF",
  },
  guestBadgeDot: {
    backgroundColor: "#94A3B8",
  },
  headerInfo: {
    flex: 1,
    marginLeft: 14,
  },
  nameRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  userNameText: {
    fontSize: 18,
    fontWeight: "800",
    color: "#0F172A",
  },
  citizenIdText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#176B87",
    marginTop: 2,
  },
  barangayText: {
    fontSize: 12,
    color: "#64748B",
    marginTop: 2,
  },
  qrHeaderBtn: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F0F9FF",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#BAE6FD",
  },
  qrBtnLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: "#176B87",
    marginTop: 2,
  },
  badgesRow: {
    flexDirection: "row",
    marginTop: 14,
    alignItems: "center",
  },
  badgeSpacer: {
    width: 8,
  },
  tabBarContainer: {
    flexDirection: "row",
    backgroundColor: "#E2E8F0",
    borderRadius: 14,
    padding: 3,
    marginBottom: 16,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
  },
  tabButtonActive: {
    backgroundColor: "#FFFFFF",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  tabButtonText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#64748B",
  },
  tabButtonTextActive: {
    color: "#176B87",
    fontWeight: "800",
  },
  sectionStack: {
    gap: 12,
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  cardHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  cardHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  cardTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#0F172A",
    marginLeft: 8,
  },
  editIconBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F0F9FF",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#BAE6FD",
  },
  editText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#176B87",
    marginLeft: 4,
  },
  infoGrid: {
    gap: 10,
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  infoContent: {
    marginLeft: 10,
    flex: 1,
  },
  infoLabel: {
    fontSize: 11,
    color: "#64748B",
    fontWeight: "500",
  },
  infoValue: {
    fontSize: 13,
    fontWeight: "600",
    color: "#0F172A",
    marginTop: 1,
  },
  infoDivider: {
    height: 1,
    backgroundColor: "#F1F5F9",
    marginVertical: 4,
  },
  twoColumnRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  columnHalf: {
    flex: 1,
  },

  /* Digital Citizen ID Preview Styles (Bottom of Personal Info) */
  citizenIdCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    overflow: "hidden",
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
    marginTop: 4,
  },
  citizenIdHeader: {
    backgroundColor: "#0F4C61",
    paddingVertical: 10,
    paddingHorizontal: 14,
    alignItems: "center",
  },
  idHeaderRow: {
    alignItems: "center",
  },
  idRepublicText: {
    fontSize: 9,
    color: "#CBD5E1",
    fontWeight: "700",
    letterSpacing: 1,
  },
  idCityText: {
    fontSize: 11,
    color: "#FFFFFF",
    fontWeight: "800",
  },
  idCardTitle: {
    fontSize: 11,
    color: "#38BDF8",
    fontWeight: "900",
    marginTop: 2,
    letterSpacing: 0.5,
  },
  idBodyRow: {
    flexDirection: "row",
    padding: 14,
    alignItems: "center",
    backgroundColor: "#FFFFFF",
  },
  idPhotoBox: {
    width: 64,
    height: 74,
    backgroundColor: "#176B87",
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  idPhotoText: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "900",
  },
  idCheckBadge: {
    position: "absolute",
    bottom: -4,
    right: -4,
    backgroundColor: "#FFFFFF",
    borderRadius: 8,
    padding: 2,
  },
  idInfoCol: {
    marginLeft: 14,
    flex: 1,
  },
  idLabel: {
    fontSize: 9,
    color: "#64748B",
    fontWeight: "700",
  },
  idValueName: {
    fontSize: 14,
    fontWeight: "800",
    color: "#0F172A",
  },
  idValueHighlight: {
    fontSize: 12,
    fontWeight: "800",
    color: "#176B87",
  },
  idValueSub: {
    fontSize: 11,
    color: "#475569",
    fontWeight: "500",
  },
  idFooterBanner: {
    backgroundColor: "#F0F9FF",
    borderTopWidth: 1,
    borderColor: "#BAE6FD",
    padding: 14,
    gap: 10,
  },
  idFooterTextStack: {
    flexDirection: "column",
  },
  idFooterNoticeTitle: {
    fontSize: 13,
    fontWeight: "800",
    color: "#0F172A",
  },
  idFooterNoticeSub: {
    fontSize: 11,
    color: "#475569",
    marginTop: 2,
    lineHeight: 16,
  },
  finishIdBtn: {
    backgroundColor: "#176B87",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  finishIdBtnText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "700",
  },

  /* Settings Tab */
  cardSectionTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: "#0F172A",
    marginBottom: 12,
  },
  settingRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 4,
  },
  settingTextStack: {
    flex: 1,
    marginRight: 12,
  },
  settingLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: "#0F172A",
  },
  settingSub: {
    fontSize: 11,
    color: "#64748B",
    marginTop: 2,
  },
  settingActionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
  },
  settingLeftIcon: {
    flexDirection: "row",
    alignItems: "center",
  },
  settingActionText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#0F172A",
    marginLeft: 10,
  },
  versionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 4,
  },
  versionLabel: {
    fontSize: 12,
    color: "#64748B",
  },
  versionValue: {
    fontSize: 12,
    fontWeight: "700",
    color: "#0F172A",
  },
  signOutBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FEF2F2",
    borderWidth: 1,
    borderColor: "#FCA5A5",
    borderRadius: 16,
    paddingVertical: 14,
    marginTop: 8,
    gap: 8,
  },
  signOutBtnText: {
    color: "#EF4444",
    fontSize: 14,
    fontWeight: "700",
  },
  /* Modals */
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.65)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  qrModalContainer: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 24,
    width: "100%",
    alignItems: "center",
  },
  qrModalHeader: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  qrModalTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#0F172A",
  },
  closeBtn: {
    padding: 4,
  },
  closeBtnText: {
    fontSize: 18,
    color: "#64748B",
    fontWeight: "700",
  },
  qrCodeBox: {
    padding: 16,
    backgroundColor: "#F8FAFC",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    marginBottom: 14,
  },
  qrCitizenName: {
    fontSize: 18,
    fontWeight: "900",
    color: "#0F172A",
  },
  qrCitizenId: {
    fontSize: 13,
    fontWeight: "700",
    color: "#176B87",
    marginBottom: 8,
  },
  qrInstruction: {
    fontSize: 12,
    color: "#64748B",
    textAlign: "center",
    marginTop: 12,
    lineHeight: 18,
  },
  qrCloseActionBtn: {
    backgroundColor: "#176B87",
    borderRadius: 14,
    paddingVertical: 12,
    width: "100%",
    alignItems: "center",
    marginTop: 20,
  },
  qrCloseActionText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "700",
  },
  editModalContainer: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 20,
    width: "100%",
  },
  modalHeaderTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#0F172A",
  },
  modalHeaderSub: {
    fontSize: 12,
    color: "#64748B",
    marginTop: 4,
    marginBottom: 16,
  },
  inputLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: "#334155",
    marginBottom: 6,
  },
  modalInput: {
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#CBD5E1",
    borderRadius: 10,
    paddingHorizontal: 12,
    height: 44,
    fontSize: 13,
    color: "#0F172A",
  },
  modalActionsRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 20,
  },
  modalCancelBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    alignItems: "center",
  },
  modalCancelText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#64748B",
  },
  modalSaveBtn: {
    flex: 1.5,
    backgroundColor: "#176B87",
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
  },
  modalSaveText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#FFFFFF",
  },

  /* ── LOGOUT MODAL STYLES ── */
  logoutOverlay: {
    flex: 1,
    backgroundColor: "rgba(10, 20, 40, 0.72)",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  logoutCard: {
    width: "100%",
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 24,
    paddingTop: 28,
    paddingBottom: 40,
    alignItems: "center",
  },
  logoutIconRing: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "#FEF2F2",
    borderWidth: 2,
    borderColor: "#FECACA",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  logoutTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#0F172A",
    textAlign: "center",
    marginBottom: 8,
  },
  logoutSubtitle: {
    fontSize: 13,
    color: "#64748B",
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 20,
    paddingHorizontal: 8,
  },
  logoutCitizenStrip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 14,
    width: "100%",
    marginBottom: 24,
  },
  logoutCitizenAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#165B7E",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  logoutCitizenAvatarText: {
    fontSize: 16,
    fontWeight: "800",
    color: "#FFFFFF",
  },
  logoutCitizenInfo: {
    flex: 1,
  },
  logoutCitizenName: {
    fontSize: 14,
    fontWeight: "700",
    color: "#0F172A",
  },
  logoutCitizenId: {
    fontSize: 11,
    color: "#64748B",
    marginTop: 2,
    fontWeight: "600",
  },
  logoutActiveBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#DCFCE7",
    borderRadius: 20,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  logoutActiveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#16A34A",
    marginRight: 4,
  },
  logoutActiveLabel: {
    fontSize: 10,
    fontWeight: "800",
    color: "#16A34A",
    letterSpacing: 0.5,
  },
  logoutActionsCol: {
    width: "100%",
    gap: 10,
    marginBottom: 20,
  },
  logoutConfirmBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#DC2626",
    borderRadius: 14,
    paddingVertical: 15,
    gap: 8,
  },
  logoutConfirmText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  logoutCancelBtn: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F1F5F9",
    borderRadius: 14,
    paddingVertical: 15,
  },
  logoutCancelText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#334155",
  },
  logoutFooterNote: {
    flexDirection: "row",
    alignItems: "center",
  },
  logoutFooterText: {
    fontSize: 11,
    color: "#94A3B8",
    fontWeight: "500",
  },

  /* ── CHANGE PASSWORD MODAL STYLES ── */
  changePasswordModalContainer: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 24,
    width: "100%",
    maxHeight: "90%",
  },
  passwordWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#CBD5E1",
    borderRadius: 10,
    paddingHorizontal: 14,
    height: 48,
    marginBottom: 10,
  },
  passwordInput: {
    flex: 1,
    height: "100%",
    fontSize: 14,
    color: "#0F172A",
  },
  eyeIconBtn: {
    padding: 6,
    justifyContent: "center",
    alignItems: "center",
  },
  modalSaveBtnDisabled: {
    backgroundColor: "#94A3B8",
    opacity: 0.7,
  },
  changePasswordErrorText: {
    color: "#EF4444",
    fontSize: 12,
    fontWeight: "600",
    marginTop: 6,
    marginBottom: 6,
  },

  /* Strength Meter Styles */
  strengthMeterContainer: {
    backgroundColor: "#F8FAFC",
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  strengthBarRow: {
    flexDirection: "row",
    gap: 6,
    height: 6,
    marginBottom: 8,
  },
  strengthBar: {
    flex: 1,
    height: "100%",
    backgroundColor: "#E2E8F0",
    borderRadius: 3,
  },
  barWeak: {
    backgroundColor: "#EF4444",
  },
  barMedium: {
    backgroundColor: "#F59E0B",
  },
  barStrong: {
    backgroundColor: "#10B981",
  },
  strengthLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
    gap: 6,
  },
  strengthPromptText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#64748B",
  },
  strengthText: {
    fontSize: 12,
    fontWeight: "800",
  },
  textWeak: {
    color: "#EF4444",
  },
  textMedium: {
    color: "#F59E0B",
  },
  textStrong: {
    color: "#10B981",
  },
  checklistContainer: {
    gap: 6,
  },
  checkItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  checkText: {
    fontSize: 11,
    fontWeight: "600",
    color: "#94A3B8",
  },
  checkTextActive: {
    color: "#334155",
  },
  keyboardAvoidOverlay: {
    flex: 1,
    width: "100%",
  },
  changePasswordScrollContent: {
    flexGrow: 1,
    paddingBottom: 8,
  },
  successToastOverlay: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.4)",
    justifyContent: "center",
    alignItems: "center",
    padding: 30,
  },
  successToastCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    paddingVertical: 32,
    paddingHorizontal: 24,
    width: "85%",
    alignItems: "center",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 15,
  },
  successToastCheckCircle: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "#10B981",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
    shadowColor: "#10B981",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 8,
  },
  successToastTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#0F172A",
    textAlign: "center",
    marginBottom: 8,
  },
  successToastSub: {
    fontSize: 13,
    color: "#64748B",
    textAlign: "center",
    lineHeight: 18,
  },
  logoutLoadingOverlay: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.65)",
    alignItems: "center",
    justifyContent: "center",
  },
  logoutLoadingCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    paddingVertical: 28,
    paddingHorizontal: 32,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 20,
    elevation: 10,
    minWidth: 240,
  },
  logoutLoadingText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#0F172A",
    marginTop: 14,
    textAlign: "center",
  },
  logoutLoadingSub: {
    fontSize: 12,
    color: "#64748B",
    marginTop: 4,
    textAlign: "center",
  },
});
