import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  keyboardContainer: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0F172A',
  },
  headerRightPlaceholder: {
    width: 42,
  },
  bannerCard: {
    borderRadius: 16,
    padding: 18,
    marginBottom: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  bannerIconWrapper: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  bannerTextWrapper: {
    flex: 1,
  },
  bannerTitle: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '700',
    marginBottom: 4,
  },
  bannerSubtitle: {
    color: 'rgba(255, 255, 255, 0.9)',
    fontSize: 13,
    lineHeight: 18,
  },
  stepIndicatorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 24,
    paddingHorizontal: 4,
  },
  stepItem: {
    alignItems: 'center',
    flex: 1,
  },
  stepCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#E2E8F0',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 6,
  },
  stepCircleActive: {
    backgroundColor: '#0284C7',
  },
  stepCircleCompleted: {
    backgroundColor: '#10B981',
  },
  stepNumber: {
    fontSize: 13,
    fontWeight: '700',
    color: '#64748B',
  },
  stepNumberActive: {
    color: '#FFFFFF',
  },
  stepLabel: {
    fontSize: 11,
    color: '#64748B',
    fontWeight: '500',
    textAlign: 'center',
  },
  stepLabelActive: {
    color: '#0284C7',
    fontWeight: '700',
  },
  stepConnector: {
    height: 2,
    flex: 0.7,
    backgroundColor: '#E2E8F0',
    marginTop: -20,
  },
  stepConnectorActive: {
    backgroundColor: '#0284C7',
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0F172A',
    marginBottom: 16,
  },
  inputGroup: {
    marginBottom: 14,
  },
  inputLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#334155',
    marginBottom: 6,
  },
  input: {
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    color: '#0F172A',
  },
  rowInputs: {
    flexDirection: 'row',
    gap: 12,
  },
  rowItem: {
    flex: 1,
  },
  selectionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
  },
  chipItem: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: '#F1F5F9',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  chipItemActive: {
    backgroundColor: '#E0F2FE',
    borderColor: '#0284C7',
  },
  chipText: {
    fontSize: 13,
    color: '#475569',
    fontWeight: '500',
  },
  chipTextActive: {
    color: '#0284C7',
    fontWeight: '700',
  },
  // District Cards
  districtCardGrid: {
    gap: 10,
    marginTop: 4,
  },
  districtCard: {
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    padding: 14,
    backgroundColor: '#F8FAFC',
  },
  districtCardActive: {
    borderColor: '#0284C7',
    backgroundColor: '#E0F2FE',
  },
  districtCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  districtCardTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1E293B',
  },
  districtCardTitleActive: {
    color: '#0369A1',
  },
  districtBadge: {
    backgroundColor: '#E2E8F0',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  districtBadgeActive: {
    backgroundColor: '#0284C7',
  },
  districtBadgeText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#475569',
  },
  districtBadgeTextActive: {
    color: '#FFFFFF',
  },
  districtCardDesc: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 4,
    lineHeight: 16,
  },
  // Dropdown Button
  dropdownTrigger: {
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 13,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  dropdownTriggerActive: {
    borderColor: '#0284C7',
    backgroundColor: '#F0F9FF',
  },
  dropdownValueText: {
    fontSize: 14,
    color: '#0F172A',
    fontWeight: '600',
  },
  dropdownHintText: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 4,
  },
  dropdownMenu: {
    marginTop: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  dropdownOptionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 13,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  dropdownOptionItemActive: {
    backgroundColor: '#E0F2FE',
  },
  dropdownOptionText: {
    fontSize: 14,
    color: '#334155',
    fontWeight: '500',
  },
  dropdownOptionTextActive: {
    color: '#0284C7',
    fontWeight: '700',
  },
  // Calendar Dropdown Styles
  calendarCard: {
    marginTop: 8,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  calendarHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  calendarNavBtn: {
    width: 34,
    height: 34,
    borderRadius: 8,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarMonthYearBtn: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: '#F1F5F9',
  },
  calendarMonthYearText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0F172A',
  },
  calendarSelectorsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  calendarDropdownBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#F1F5F9',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  calendarDropdownBtnActive: {
    backgroundColor: '#E0F2FE',
    borderColor: '#0284C7',
  },
  calendarDropdownBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#0F172A',
  },
  calendarMonthGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 12,
    padding: 10,
    backgroundColor: '#F8FAFC',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  calendarMonthGridCell: {
    width: '31%',
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 6,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  calendarMonthGridCellActive: {
    backgroundColor: '#0284C7',
    borderColor: '#0284C7',
  },
  calendarMonthGridText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#334155',
  },
  calendarMonthGridTextActive: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  calendarYearDropdownContainer: {
    maxHeight: 180,
    marginBottom: 12,
    padding: 6,
    backgroundColor: '#F8FAFC',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  calendarYearOption: {
    paddingVertical: 9,
    paddingHorizontal: 14,
    borderRadius: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  calendarYearOptionActive: {
    backgroundColor: '#0284C7',
  },
  calendarYearOptionText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#334155',
  },
  calendarYearOptionTextActive: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  calendarWeekRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 8,
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  calendarWeekLabel: {
    width: 36,
    textAlign: 'center',
    fontSize: 11,
    fontWeight: '700',
    color: '#94A3B8',
  },
  calendarDaysGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  calendarDayCell: {
    width: `${100 / 7}%`,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 2,
    borderRadius: 8,
  },
  calendarDayCellActive: {
    backgroundColor: '#0284C7',
  },
  calendarDayText: {
    fontSize: 13,
    fontWeight: '500',
    color: '#1E293B',
  },
  calendarDayTextActive: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
  // Modal for Barangay Search
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContainer: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '80%',
    paddingTop: 16,
    paddingBottom: Platform.OS === 'ios' ? 34 : 20,
    paddingHorizontal: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  modalTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#0F172A',
  },
  modalCloseButton: {
    padding: 6,
  },
  modalSearchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F1F5F9',
    borderRadius: 10,
    paddingHorizontal: 12,
    marginTop: 12,
    marginBottom: 8,
  },
  modalSearchInput: {
    flex: 1,
    paddingVertical: 10,
    paddingLeft: 8,
    fontSize: 14,
    color: '#0F172A',
  },
  modalList: {
    marginTop: 8,
    maxHeight: 320,
  },
  modalListItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    borderRadius: 8,
  },
  modalListItemActive: {
    backgroundColor: '#E0F2FE',
  },
  modalListItemText: {
    fontSize: 14,
    color: '#334155',
    fontWeight: '500',
  },
  modalListItemTextActive: {
    color: '#0284C7',
    fontWeight: '700',
  },
  emptyListText: {
    textAlign: 'center',
    color: '#94A3B8',
    paddingVertical: 24,
    fontSize: 14,
  },
  // Upload Box
  uploadBox: {
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: '#CBD5E1',
    borderRadius: 14,
    backgroundColor: '#F8FAFC',
    padding: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  uploadBoxActive: {
    borderColor: '#10B981',
    backgroundColor: '#ECFDF5',
  },
  uploadTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1E293B',
    marginTop: 10,
  },
  uploadSubtitle: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 4,
    textAlign: 'center',
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
  },
  secondaryButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#475569',
  },
  primaryButton: {
    flex: 2,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: '#0284C7',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0284C7',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
  },
  primaryButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  errorText: {
    color: '#EF4444',
    fontSize: 13,
    marginBottom: 12,
    fontWeight: '500',
  },
  successContainer: {
    alignItems: 'center',
    paddingVertical: 32,
  },
  successIconBadge: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#D1FAE5',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  successTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#0F172A',
    marginBottom: 8,
    textAlign: 'center',
  },
  successMessage: {
    fontSize: 14,
    color: '#64748B',
    textAlign: 'center',
    lineHeight: 22,
    paddingHorizontal: 16,
    marginBottom: 24,
  },
  infoBox: {
    backgroundColor: '#F0F9FF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#BAE6FD',
    padding: 16,
    width: '100%',
    marginBottom: 24,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 4,
  },
  infoLabel: {
    fontSize: 13,
    color: '#0369A1',
  },
  infoValue: {
    fontSize: 13,
    fontWeight: '700',
    color: '#0C4A6E',
  },
  // Photo Preview & Picker Styles
  photoPreviewCard: {
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#10B981',
    backgroundColor: '#F8FAFC',
    overflow: 'hidden',
    marginTop: 8,
  },
  photoPreviewImage: {
    width: '100%',
    height: 180,
    backgroundColor: '#E2E8F0',
  },
  photoPreviewFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  photoStatusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  photoStatusText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#10B981',
  },
  photoActionsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  photoActionBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: '#F0F9FF',
    borderWidth: 1,
    borderColor: '#BAE6FD',
  },
  photoActionBtnText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#0284C7',
  },
  photoRemoveBtn: {
    backgroundColor: '#FEF2F2',
    borderColor: '#FECACA',
  },
  photoRemoveBtnText: {
    color: '#EF4444',
  },
  // Photo Source Picker Modal
  pickerModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.65)',
    justifyContent: 'flex-end',
  },
  pickerModalContent: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: 36,
  },
  pickerModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  pickerModalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0F172A',
  },
  pickerModalSubtitle: {
    fontSize: 13,
    color: '#64748B',
    marginBottom: 20,
  },
  pickerOptionsList: {
    gap: 12,
    marginBottom: 16,
  },
  pickerOptionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 14,
    padding: 16,
    gap: 14,
  },
  pickerOptionIconBox: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#E0F2FE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pickerOptionTextCol: {
    flex: 1,
  },
  pickerOptionLabel: {
    fontSize: 15,
    fontWeight: '700',
    color: '#0F172A',
  },
  pickerOptionDesc: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 2,
  },
  pickerCancelBtn: {
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pickerCancelText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#475569',
  },
  // REWORK / CORRECTION BANNER
  reworkBanner: {
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#EA580C',
    backgroundColor: '#FFF7ED',
    padding: 16,
    marginBottom: 20,
  },
  reworkBannerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 8,
  },
  reworkBannerTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#C2410C',
  },
  reworkRemarksBox: {
    backgroundColor: '#FFEDD5',
    borderRadius: 10,
    padding: 12,
    marginBottom: 8,
  },
  reworkRemarksLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#9A3412',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  reworkRemarksText: {
    fontSize: 13,
    color: '#7C2D12',
    lineHeight: 18,
    fontWeight: '500',
  },
  reworkInstructionsText: {
    fontSize: 12,
    color: '#9A3412',
    lineHeight: 16,
  },
  // GUARD SCREEN (Under Review / Approved / Rejected)
  guardCard: {
    borderRadius: 20,
    borderWidth: 1,
    padding: 24,
    alignItems: 'center',
    marginBottom: 24,
  },
  guardIconBox: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  guardTitle: {
    fontSize: 20,
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: 8,
  },
  guardSubtitle: {
    fontSize: 13,
    lineHeight: 20,
    textAlign: 'center',
    marginBottom: 20,
    paddingHorizontal: 8,
  },
  guardDetailsBox: {
    width: '100%',
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    marginBottom: 20,
  },
  guardRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  guardRowLabel: {
    fontSize: 12,
    fontWeight: '600',
  },
  guardRowValue: {
    fontSize: 13,
    fontWeight: '700',
  },
  // CITIZEN ID CARD PREVIEW
  citizenIdCard: {
    width: '100%',
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: '#0284C7',
    backgroundColor: '#0F172A',
    padding: 18,
    marginBottom: 20,
    shadowColor: '#0284C7',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 4,
  },
  citizenIdCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#334155',
    paddingBottom: 10,
    marginBottom: 14,
  },
  citizenIdCardLogoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  citizenIdCardCityName: {
    color: '#38BDF8',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.8,
  },
  citizenIdCardSub: {
    color: '#94A3B8',
    fontSize: 10,
    fontWeight: '600',
  },
  citizenIdCardBody: {
    flexDirection: 'row',
    gap: 14,
    alignItems: 'center',
  },
  citizenIdCardPhoto: {
    width: 80,
    height: 80,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#38BDF8',
    backgroundColor: '#1E293B',
  },
  citizenIdCardInfo: {
    flex: 1,
  },
  citizenIdNumberLabel: {
    color: '#94A3B8',
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  citizenIdNumberValue: {
    color: '#F8FAFC',
    fontSize: 15,
    fontWeight: '900',
    letterSpacing: 1,
    marginBottom: 6,
  },
  citizenIdCardName: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 2,
  },
  citizenIdCardBarangay: {
    color: '#38BDF8',
    fontSize: 12,
    fontWeight: '600',
  },
  // 1x1 Photo Specific Box
  photo1x1Container: {
    alignItems: 'center',
    marginVertical: 4,
  },
  photo1x1Preview: {
    width: 140,
    height: 140,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#10B981',
    backgroundColor: '#FFFFFF',
  },
  // Digital Signature Specific Box
  signaturePreviewBox: {
    width: '100%',
    height: 110,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#10B981',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  signatureImage: {
    width: '90%',
    height: '80%',
  },
  signatureOptionRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 8,
  },
  signatureOptionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    backgroundColor: '#F8FAFC',
  },
  signatureOptionBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#334155',
  },
  // Drawing Canvas Modal
  signatureModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.75)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  signatureModalCard: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 8,
  },
  signatureCanvasWrapper: {
    width: '100%',
    height: 200,
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    marginVertical: 14,
    overflow: 'hidden',
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
  signatureBaseline: {
    position: 'absolute',
    bottom: 40,
    left: 20,
    right: 20,
    height: 1,
    backgroundColor: '#E2E8F0',
    borderStyle: 'dashed',
    borderWidth: 0.5,
    borderColor: '#CBD5E1',
  },
  signatureBaselineLabel: {
    position: 'absolute',
    bottom: 24,
    left: 20,
    fontSize: 10,
    color: '#94A3B8',
    fontWeight: '600',
  },
  signatureModalActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 6,
  },
});

